name: iOS Build & Test Check

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Build and run tests
        run: |
          set -o pipefail && xcodebuild \
            -project GlobeSales.xcodeproj \
            -scheme GlobeSales \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro' \
            test | xcpretty
